---
- hosts: all
  remote_user: "{{ ansible_user }}"
  any_errors_fatal: true
  order: sorted

  roles:
    # - stopProcesses
    # - logicalVolumes
    # - dockerProcesses
    # - dockerInfo
    # - dockerContainers
    # - createUser
    # - createDirectories
    # - docker
    - testRole
