---
- hosts: all
  remote_user: "{{ ansible_user }}"
  any_errors_fatal: true
  order: sorted

  pre_tasks:
    - name: Validate we run with the correct Ansible version
      delegate_to: hostvars[inventory_hostname]['ansible_python_version']
      assert:
        that:
          - ansible_version is defined
          - ansible_version.full is version('2.8.0.0', '>=')
          - ansible_python_version is defined
          - ansible_python_version is version('3.6.0', '>=')
        fail_msg: "'Python' version must be 3.6.0 and Ansible 2.8.0 minimal version."
      run_once: True

  roles:
    # - stopProcesses
    # - logicalVolumes
    # - dockerProcesses
    # - dockerInfo
    # - dockerContainers
    # - createUser
    # - createDirectories
    - docker
