---
- hosts: all
  remote_user: "{{ ansible_user }}"
  any_errors_fatal: true
  order: sorted

  pre_tasks:
    - name: Include vars for environment
      ansible.builtin.include_vars:
        file: "{{ env_variable }}.yml"

  roles:
    # - stopProcesses
    # - logicalVolumes
    # - dockerProcesses
    # - dockerInfo
    # - dockerContainers
    # - createUser
    # - createDirectories
    # - docker
    - testRole
