---
# tasks file for dockerContainers
- name: Get info on docker host
  docker_host_info:
    containers: yes
  register: result

- name: Containers Filter
  docker_host_info:
    containers: yes
    containers_filters:
      name: "nobel"
  register: data
  when: result.containers | length != 0

- name: Debug Filter
  debug:
    var: data.containers
