---
# tasks file for docker
- name: Build an image and push it to a private repo
  docker_image:
    build:
      path: /tmp/mongo
    name: riskit.docker.itcm.oneadr.net/ripl-mongo
    tag: 1.0.1
    # push: yes
    source: build
