---
- name: Create mongo directory
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    recurse: "{{ item.recurse }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ dockerDir }}"

- name: Copy files to directory
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ dockerFiles }}"
